"""Tool domain facade for v4.0."""

from dare_framework3_4.tool.component import (
    IToolProvider,
    ITool,
    ISkill,
    ICapabilityProvider,
    IProtocolAdapter,
    IMCPClient,
)
from dare_framework3_4.tool.interfaces import IToolGateway, IExecutionControl
from dare_framework3_4.tool.types import (
    CapabilityDescriptor,
    CapabilityType,
    Checkpoint,
    Evidence,
    ExecutionSignal,
    HumanApprovalRequired,
    PauseRequested,
    CancelRequested,
    RunContext,
    ToolDefinition,
    ToolErrorRecord,
    ToolResult,
    ToolType,
)
from dare_framework3_4.tool.internal import (
    DefaultToolGateway,
    NativeToolProvider,
    ProtocolAdapterProvider,
    GatewayToolProvider,
    MCPAdapter,
    NoOpMCPClient,
    RunContextState,
    FileExecutionControl,
    NoOpTool,
    NoOpSkill,
    RunCommandTool,
    ReadFileTool,
    SearchCodeTool,
    WriteFileTool,
    EditLineTool,
)

__all__ = [
    "IToolProvider",
    "ITool",
    "ISkill",
    "ICapabilityProvider",
    "IProtocolAdapter",
    "IMCPClient",
    "IToolGateway",
    "IExecutionControl",
    "CapabilityDescriptor",
    "CapabilityType",
    "Checkpoint",
    "Evidence",
    "ExecutionSignal",
    "HumanApprovalRequired",
    "PauseRequested",
    "CancelRequested",
    "RunContext",
    "ToolDefinition",
    "ToolErrorRecord",
    "ToolResult",
    "ToolType",
    "DefaultToolGateway",
    "NativeToolProvider",
    "ProtocolAdapterProvider",
    "GatewayToolProvider",
    "MCPAdapter",
    "NoOpMCPClient",
    "RunContextState",
    "FileExecutionControl",
    "NoOpTool",
    "NoOpSkill",
    "RunCommandTool",
    "ReadFileTool",
    "SearchCodeTool",
    "WriteFileTool",
    "EditLineTool",
]
